### ISSUE TITLE
Peering as first class citizen

### ISSUE THREAD

**Issue by dstelter** [invliD/lana-dashboard#15]
It would be nice to maintain tunnels and peerings as separate models. Tunnels connect two distinct locations, peerings exchange routes between AS.

Peering could be (automatically) augmented with observed routing data, as seen by the participant's routing agent.

**Comment by invliD** [comment]
@dstelter Any ideas what attributes a peering should have? The only thing I can think of is whether bfd is enabled or not. Do we want to duplicate the both parties of a peering like in tunnels (both endpoints would need an AS and an internal IP address, quite similar to tunnels)?
Or do we want to _reference_ tunnels instead? What about peerings that are not established through a tunnel (like direct ethernet links)?

**Comment by dstelter** [comment]
Don't we have a host model we can use to reference endpoints?
The most important attribute of a peering are the exchanged routes.

**Comment by invliD** [comment]
But the routes are dynamic. Do you want to specify anything manually there?

**Comment by invliD** [comment]
@dstelter Any comments?

**Comment by invliD** [comment]
@dstelter What about giving the user two options: Either create a peering on an existing tunnel – reusing all its attributes like peer IP, or create a peering manually between two hosts – using that host's internal ip addresses as peer address.

**Comment by dstelter** [comment]
SGTM, this would solve all my problems and make the world a better place.

**Comment by invliD** [comment]
Tunnel-based peerings implemented in d8e2db6.
