### ISSUE TITLE
Contact information per institution

### ISSUE THREAD

**Issue by dstelter** [invliD/lana-dashboard#2]
Store and display an email address for each institution.

Optionally some other fields, like Skype/Jabber. It could be a simple free-form description box.

**Comment by invliD** [comment]
@dstelter @wilkemeyer Institutions now have an abuse email (I'll make that field required once all institutions have one in production, #4) and users now have Skype/XMPP data and a plain text field. In addition, users can choose to display their account email on the profile page.
Please confirm on production so I can close this issue.

**Comment by dstelter** [comment]
Looking good, thanks.
