### ISSUE TITLE
Move host details to host

### ISSUE THREAD

**Issue by jgraichen** [invliD/lana-dashboard#22]
Can we move host details such as Hostname, external IPv4 address, internal IPv4 address and public key to the AS resource? As of now we have to duplicate lots of information for each tunnel terminating on the same AS. I would be great if some information, such as internal IPv4 address and public key, could be "overriden" on the tunnel because I have a small number of tunnels with different IPs and keys.

**Comment by mswart** [comment]
I think the better place would be the host itself.

**Comment by jgraichen** [comment]
Yes, absolutely. Forgot there is a host while writing this ;)

**Comment by invliD** [comment]
Overriding the internal IP on a tunnel is a great idea, I already planned moving the information, but I wasn't sure how to handle different internal IPs.

**Comment by invliD** [comment]
Closed in 5a7a27f.
