### ISSUE TITLE
DKIM sign outgoing emails

### ISSUE THREAD

**Issue by jgraichen** [invliD/lana-dashboard#25]
An actual cryptographic signature on LANA mails would be a good indicator that emails are not forged, not modified and actual created by LANA.

**Comment by invliD** [comment]
Isn't this a mail server issue? As far as I understand DKIM, the outgoing mail server needs to sign the emails with its key for the domain, not the application.

**Comment by jgraichen** [comment]
Well, usually the mail server is DKIM signing, but as it's only headers it could be done by the application (still should not). I didn't find a better place to report this ;)
