### ISSUE TITLE
Add "clear override" for IPv4 address on a tunnel endpoint

### ISSUE THREAD

**Issue by invliD** [invliD/lana-dashboard#29]
It's currently impossible not to specify an IPv4 address on a tunnel endpoint if the host has a tunnel address, because that will be used if not overridden. For tunnels where the address is dynamic or unknown, it should be possible to override it with "none".

**Comment by jgraichen** [comment]
How about setting the override to null when a blank string is passed via the form?

**Comment by invliD** [comment]
What's the difference between "no override" and "override to blank", then?

**Comment by jgraichen** [comment]
What would override with blank mean? Unset internal IPv4? Imo that would be invalid anyways. I do not see a use case where override should by anything else but a valid non-null IPv4.

**Comment by invliD** [comment]
That's the point of this issue. I do see that case, outlined above. There are cases where the tunnel endpoint does not have a fixed IP. In that case I don't want "the usual" tunnel IP to appear, because that's just incorrect. There has to be a way to specify "no" IP address for the endpoint, even though the host "usually" has a tunnel IP.

**Comment by jgraichen** [comment]
The internal tunnel IPv4 changes? Didn't expect that.

I that's the case how about placing a checkbox behind the input to mark it for clearance?

**Comment by invliD** [comment]
That's the plan. I only created this issue so I won't forget.

**Comment by jgraichen** [comment]
Or you add an flag to mark the endpoint as "dynamic" instead of a "none" IPv4 to state the actual fact.

**Comment by invliD** [comment]
Closed in db89653.
